name: Reusable workflow - dump context

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print job_workflow_ref
        run: echo ${{ github.job_workflow_ref }}
