# Based on https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: Reusable workflow that runs local action

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      # Local actions need to be checked out first
      - uses: actions/checkout@v3

      - run: ls -la

      - run: cat ./README.md

      - uses: ./local-actions/say-hello
        with:
          username: ${{ inputs.username }}
