# Based on https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: Reusable workflow that runs local action

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  use-local-action:
    runs-on: ubuntu-latest
    steps:
      # Filesystem path actions need to be cloned first
      - uses: actions/checkout@v3
        with:
          repository: 'cross-repo-scenarios/reusable-workflows'  # without this, the executing repository will be checked out

      - uses: ./local-actions/say-hello
        with:
          username: ${{ inputs.username }}


  use-local-action-via-qualified-path:
    runs-on: ubuntu-latest
    steps:
      # By qualifying the path to this repository's action we can skip cloning the repository
      - uses: cross-repo-scenarios/reusable-workflows/local-actions/say-hello@main
        with:
          username: ${{ inputs.username }}
