# Based on https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-reusable-workflow
name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      # Local actions need to be checked out first
      - uses: actions/checkout@v3
      
      - uses: ./.github/workflows/my-action
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}
